---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-simple-deployment
  namespace: example-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver-simple-app
  template:
    metadata:
      labels:
        app: webserver-simple-app
    spec:
      containers:
        - name: webserver-simple-container
          image: docker.pkg.github.com/ianmiell/example-gitops-app/example-gitops-app:latest docker.pkg.github.com/ianmiell/example-gitops-app/example-gitops-app:0a1a1569b260 docker.pkg.github.com/ianmiell/example-gitops-app/example-gitops-app:1183d36eacdd
          command:
            - python
            - -m
            - http.server
      imagePullSecrets:
        - name: regcred
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: webserver-simple-service
  namespace: example-gitops
spec:
  selector:
    app: webserver-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
