---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-example-deployment
  namespace: gitops-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-example-app
  template:
    metadata:
      labels:
        app: gitops-example-app
    spec:
      containers:
        - name: gitops-example-container
          image: docker.pkg.github.com/ianmiell/gitops-example-app/gitops-example-app:dd231b980eaa
          command:
            - python
            - -m
            - http.server
      imagePullSecrets:
        - name: regcred
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: gitops-example-service-service
  namespace: gitops-example
spec:
  selector:
    app: gitops-example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
