name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: example-gitops-app-trigger

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install kubectl
        run: |
          sudo apt upgrade && sudo apt install -y curl && curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && sudo mv kubectl /usr/local/bin
      - name: set up kubectl config
        run: |
          mkdir -p /home/runner/.kube echo "${EXAMPLE_GITOPS_DEPLOY_KUBECTL}" > /home/runner/.kube/config && echo ~ && cat /home/runner/.kube/config && echo ~
      - name: check kubectl config
        run: |
          kubectl cluster-info
