name: Update Image Reference
on:
  repository_dispatch:
    types: example-gitops-app-trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v2
      - name: Update Version In Checked-Out Code
        if: ${{ github.event.client_payload.image }}
        run: |
          sed -i "s@\(.*image:\).*@\1 ${{ github.event.client_payload.image }}@" ${GITHUB_WORKSPACE}/workloads/webserver.yaml
      - name: Commit The New Image Reference
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event.client_payload.image }}
        with:
          commit_message: Deploy new image ${{ github.event.client_payload.image }}
          branch: main
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: Example GitOps Bot
          commit_user_email: example-gitops-bot@container-solutions.com
          commit_author: Example GitOps Bot <example-gitops-bot@container-solutions.com>
